input:
  file:
    paths: ["raw_example.json"]

pipeline:
  processors:
    - mapping: |
        root.device_id = this.id
        root.temperature = this.temp.number()
        root.humidity = this.hum.number()
        root.timestamp = this.time.parse_timestamp("02-01-2006 15:04:05").format_timestamp("2006-01-02T15:04:05Z")

output:
  http_client:
    url: http://127.0.0.1:8000/ingest
    verb: POST
    headers:
      Content-Type: application/json
