input:
  mqtt:
    urls:
      - tcp://localhost:1883
    topics:
      - sensors/#
    client_id: bento-consumer
    qos: 1

pipeline:
  processors:
    - mapping: |
        root = {
          "device_id": this.id,
          "temperature": this.temp.number(),
          "humidity": this.hum.number(),
          "timestamp": this.time
        }

output:
  sql_insert:
    driver: postgres
    dsn: postgres://postgres:postgres@localhost:5432/sensor_data?sslmode=disable
    table: sensor_data
    columns:
      - device_id
      - temperature
      - humidity
      - timestamp
    args_mapping: |
      root = [
        this.device_id,
        this.temperature,
        this.humidity,
        this.timestamp
      ]
