http:
  address: 0.0.0.0:4197

input:
  http_server:
    path: /ingest
    allowed_verbs: [ POST ]

pipeline:
  processors:
    # 🔥 Divide el array en mensajes individuales
    - unarchive:
        format: json_array

    # 🔥 Extrae la colección
    - mapping: |
        meta collection = this._collection
        root = this.without("_collection")

output:
  switch:
    cases:

      - check: meta("collection") == "readings"
        output:
          http_client:
            url: http://host.docker.internal:8090/api/collections/readings/records
            verb: POST
            headers:
              Content-Type: application/json

      - check: meta("collection") == "urgent_alerts"
        output:
          http_client:
            url: http://host.docker.internal:8090/api/collections/urgent_alerts/records
            verb: POST
            headers:
              Content-Type: application/json

      - output:
          stdout:
            codec: lines