# /core/benthos.yaml - compatible con v4.11.0
input:
  stdin:
    codec: lines 

pipeline:
  processors:
    - bloblang: |
        root.sensor = this.sensor
        root.value = this.value
        root.time = this.time

output:
  http_client:
    url: "${POCKETBASE_URL}/api/collections/readings/records"
    verb: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer ${POCKETBASE_TOKEN}"
    batching:
      count: 50
      period: 5s
    retries: 5
    retry_period: 1s
    max_retry_backoff: 30s

logger:
  level: INFO

http:
  address: "0.0.0.0:0"